development:
  adapter: mysql 
  encoding: utf8 
  database: catamonitor_development
  username: root 
  password: 

test:
  adapter: mysql 
  encoding: utf8 
  database: catamonitor_test
  username: root
  password: 
    
production:
  adapter: mysql 
  encoding: utf8 
  database: catamonitor
  username: catamonitor
  password: catamonitor
